# Generated by Django 3.2.2 on 2021-06-20 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('sellerid', models.AutoField(primary_key=True, serialize=False)),
                ('sellertoken', models.CharField(max_length=100)),
                ('sellertitle', models.CharField(max_length=200)),
                ('sellerEmail', models.CharField(max_length=100)),
                ('sellerEmailConfirmed', models.BooleanField(null=True)),
                ('sellerActive', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Modify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellerModifiedOn', models.DateTimeField(auto_now_add=True)),
                ('sellerModifiedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.userprofileinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Create',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellerCreatedOn', models.DateTimeField(auto_now_add=True)),
                ('sellerCreatedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.userprofileinfo')),
            ],
        ),
    ]
